version: '2'
services:

  prometheus:
    image: quay.io/prometheus/prometheus
    ports:
      - 9090:9090
    volumes:
      - /home/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: quay.io/prometheus/node-exporter
    ports:
      - 9100:9100
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs

  grafana:
      image: Grafana/Grafana
      ports:
        - 3000:3000
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin

  influxdb:
      image: influxdb:1.3.5
      command: -config /etc/influxdb/influxdb.conf
      ports:
        - 8086:8086
      environment:
        - INFLUXDB_DB=prometheus
        - INFLUXDB_ADMIN_ENABLED=true
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=admin
        - INFLUXDB_USER=prom
        - INFLUXDB_USER_PASSWORD=prom


